config/routes.rb
Rails.application.routes.draw do
  resources :daily_tasks

end

app/models/daily_task.rb
class DailyTask < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production" 
end

app/controllers/daily_tasks_controller.rb
class DailyTasksController < ApplicationController
  before_action :set_daily_task, only: [:show, :edit, :update, :destroy]

  # GET /daily_tasks
  # GET /daily_tasks.json
  def index
    @daily_tasks = DailyTask.all
  end

  # GET /daily_tasks/1
  # GET /daily_tasks/1.json
  def show
  end

  # GET /daily_tasks/new
  def new
    @daily_task = DailyTask.new
  end

  # GET /daily_tasks/1/edit
  def edit
  end

  # POST /daily_tasks
  # POST /daily_tasks.json
  def create
    @daily_task = DailyTask.new(daily_task_params)

    respond_to do |format|
      if @daily_task.save
        format.html { redirect_to @daily_task, notice: 'Daily task was successfully created.' }
        format.json { render :show, status: :created, location: @daily_task }
      else
        format.html { render :new }
        format.json { render json: @daily_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_tasks/1
  # PATCH/PUT /daily_tasks/1.json
  def update
    respond_to do |format|
      if @daily_task.update(daily_task_params)
        format.html { redirect_to @daily_task, notice: 'Daily task was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_task }
      else
        format.html { render :edit }
        format.json { render json: @daily_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_tasks/1
  # DELETE /daily_tasks/1.json
  def destroy
    @daily_task.destroy
    respond_to do |format|
      format.html { redirect_to daily_tasks_url, notice: 'Daily task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_task
      @daily_task = DailyTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_task_params
      params.require(:daily_task).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_tasks_helper.rb
module DailyTasksHelper
end

app/views/daily_tasks/_form.html.erb
<%= form_for(@daily_task) do |f| %>
  <% if @daily_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily_task.errors.count, "error") %> prohibited this daily_task from being saved:</h2>

      <ul>
      <% @daily_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_tasks/edit.html.erb
<h1>Editing Daily Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_task %> |
<%= link_to 'Back', daily_tasks_path %>

app/views/daily_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Daily Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_tasks.each do |daily_task| %>
      <tr>
        <td><%= daily_task.title %></td>
        <td><%= daily_task.user_id %></td>
        <td><%= link_to 'Show', daily_task %></td>
        <td><%= link_to 'Edit', edit_daily_task_path(daily_task) %></td>
        <td><%= link_to 'Destroy', daily_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily task', new_daily_task_path %>

app/views/daily_tasks/new.html.erb
<h1>New Daily Task</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_tasks_path %>

app/views/daily_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @daily_task.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @daily_task.user_id %>
</p>

<%= link_to 'Edit', edit_daily_task_path(@daily_task) %> |
<%= link_to 'Back', daily_tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>